import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import styles from '../styles/Home.module.css'
import { load } from "../src/func";
import Link from 'next/link';


export default function Home() {

  const [blogList, setBlogList] = useState([]);
  const [addressAccount, setAddressAccount] = useState(null);
  const [contract, setContract] = useState(null);
  const [refresh, setRefresh] = useState(true);

  // const handleInputChange = (e) => setInput(e.currentTarget.value);
  // const handleAddTask = async () => {
  //   await contract.createTask(input, {from: addressAccount});
  //   setInput('');
  //   setRefresh(true);
  // };
  // const handleDone = async (id) => {
  //   await contract.toogleCompleted(id, {from: addressAccount});
  //   setRefresh(true);
  // }

  const loadBlogs = () => {
    load().then((e) => {
      setAddressAccount(e.addressAccount);
      setBlogList(e.blogs);
      console.log(e.blogs);
      setContract(e.blogContract);
    });
  }

  useEffect(() => {
    if (!refresh) return;

    setRefresh(false);

    load().then((e) => {
      setAddressAccount(e.addressAccount);
      setBlogList(e.blogs);
      console.log(e.blogs);
      setContract(e.blogContract);
    });
  });


  return (
    <div className={styles.container}>
      <Head>
        <title>W3 Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <h1>Latest Blogs</h1>
      <Link href={"/addblog"} passHref><button>Add Blog</button></Link>
      <button onClick={loadBlogs}></button>

      <h3>Blogs Count {blogList.length}</h3>
      

      
    </div>
  )
}
